# Prettier friendly markdownlint config (all formatting rules disabled)
extends: markdownlint/style/prettier

# Override individual rules based on our README files
first-line-heading: false
no-inline-html:
  allowed_elements:
    - a
    - picture
    - source
    - img
    - p
